vich_uploader:
    db_driver: orm

    mappings:
        poster_thumb:
            uri_prefix: /img/poster/thumbs
            upload_destination: '%kernel.project_dir%/public/img/poster/thumbs'
            namer:
                service: vich.uploader
                options: { property: 'abstract.ImdisId' } # supposing that the object contains a "slug" attribute or a "getSlug" method
